services:
  runner:
    image: github-runner:latest
    build:
      context: .
      args:
        ARCHITECTURE: 'arm'
        RUNNER_VERSION: '2.321.0'
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}
    #env_file:
    #  - ./vars.env
